POST http://localhost:7070/service-records/import/CR48908
Content-Type: application/json

###

POST http://localhost:7070/auth/register
Content-Type: application/json

{
  "username": "bob6",
  "password": "1234"
}

###

POST http://localhost:7070/auth/login
Content-Type: application/json

{
"username": "bob3",
"password": "1234"
}

###

POST http://localhost:7070/cars/2/modifications
Content-Type: application/json

{
  "name": "Nye bremser",
  "category": "REPAIR",
  "date": "2026-10-07",
  "cost": 2500,
  "description": "Nye for- og bagbremser"
}

###
POST http://localhost:7070/expenses/2/create
Content-Type: application/json

{
  "date": "2026-10-07",
  "category": "FUEL",
  "amount": 600,
  "description": "Tanket bilen"
}